/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AccountService } from './services/account.service';
import { AdminService } from './services/admin.service';
import { EspaceFormateurService } from './services/espace-formateur.service';
import { FormationService } from './services/formation.service';
import { InscriptionService } from './services/inscription.service';
import { StatistiqueService } from './services/statistique.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AccountService,
    AdminService,
    EspaceFormateurService,
    FormationService,
    InscriptionService,
    StatistiqueService,
    ApiConfiguration
  ],
})
export class E_TrainingModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<E_TrainingModule> {
    return {
      ngModule: E_TrainingModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: E_TrainingModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('E_TrainingModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
