/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminCreateFormateurViewModel } from './models/admin-create-formateur-view-model';
export type { AdminUpdateFormateurViewModel } from './models/admin-update-formateur-view-model';
export type { AuthResponseViewModel } from './models/auth-response-view-model';
export type { CreateFormationViewModel } from './models/create-formation-view-model';
export type { EtudiantInscritViewModel } from './models/etudiant-inscrit-view-model';
export type { FormateurEspaceViewModel } from './models/formateur-espace-view-model';
export type { FormateurInfoViewModel } from './models/formateur-info-view-model';
export type { FormateurViewModel } from './models/formateur-view-model';
export type { Formation } from './models/formation';
export type { FormationDetailViewModel } from './models/formation-detail-view-model';
export type { FormationFormateur } from './models/formation-formateur';
export type { Inscription } from './models/inscription';
export type { InscriptionViewModel } from './models/inscription-view-model';
export type { LoginViewModel } from './models/login-view-model';
export type { PasswordResetViewModel } from './models/password-reset-view-model';
export type { PointStatistique } from './models/point-statistique';
export type { ProblemDetails } from './models/problem-details';
export type { RegisterViewModel } from './models/register-view-model';
export { Role } from './models/role';
export type { StatistiqueAdminViewModel } from './models/statistique-admin-view-model';
export type { StatistiqueEtudiantViewModel } from './models/statistique-etudiant-view-model';
export type { StatistiqueEvolutionViewModel } from './models/statistique-evolution-view-model';
export type { StatistiqueFormateurViewModel } from './models/statistique-formateur-view-model';
export type { StatistiqueFormationParPeriode } from './models/statistique-formation-par-periode';
export type { StatistiqueFormationParSpecialite } from './models/statistique-formation-par-specialite';
export type { StatistiqueGlobaleViewModel } from './models/statistique-globale-view-model';
export { StatutInscription } from './models/statut-inscription';
export type { UserStatusViewModel } from './models/user-status-view-model';
export type { Utilisateur } from './models/utilisateur';
