/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCreateFormateurViewModel {
  Email: string;
  Nom: string;
  Prenom: string;
  Specialite: string;
}
