/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EtudiantInscritViewModel {
  DateInscription?: string;
  Email?: string | null;
  EtudiantId?: string | null;
  Nom?: string | null;
  Prenom?: string | null;
}
