/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormateurInfoViewModel {
  Nom?: string | null;
  Prenom?: string | null;
  Specialite?: string | null;
}
