/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormationDetailViewModel } from '../models/formation-detail-view-model';
export interface FormateurEspaceViewModel {
  Email?: string | null;
  Formations?: Array<FormationDetailViewModel> | null;
  Id?: string | null;
  Nom?: string | null;
  Prenom?: string | null;
  Specialite?: string | null;
}
