/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EtudiantInscritViewModel } from '../models/etudiant-inscrit-view-model';
export interface FormationDetailViewModel {
  DateDebut?: string;
  DateFin?: string;
  Description?: string | null;
  EtudiantsInscrits?: Array<EtudiantInscritViewModel> | null;
  FormationId?: string | null;
  PlacesDisponibles?: number;
  Salle?: string | null;
  Titre?: string | null;
}
