/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormateurViewModel {
  Email?: string | null;
  Id?: string | null;
  MotDePasseTemporaire?: string | null;
  Nom?: string | null;
  Prenom?: string | null;
  Specialite?: string | null;
  UtilisateurActive?: boolean;
}
