/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Formation } from '../models/formation';
import { Utilisateur } from '../models/utilisateur';
export interface FormationFormateur {
  Formateur: Utilisateur;
  FormateurId: string;
  Formation: Formation;
  FormationId: string;
}
