/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Formation } from '../models/formation';
import { StatutInscription } from '../models/statut-inscription';
import { Utilisateur } from '../models/utilisateur';
export interface Inscription {
  DateInscription?: string;
  Etudiant?: Utilisateur;
  EtudiantId?: string | null;
  Formation?: Formation;
  FormationId?: string | null;
  Id?: string | null;
  Statut?: StatutInscription;
}
