/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatutInscription } from '../models/statut-inscription';
export interface InscriptionViewModel {
  DateInscription?: string;
  EtudiantId?: string | null;
  FormationId?: string | null;
  Id?: string | null;
  NomEtudiant?: string | null;
  NomFormation?: string | null;
  Statut?: StatutInscription;
}
