/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterViewModel {
  ConfirmPassword?: string | null;
  Email: string;
  Nom: string;
  Password: string;
  Prenom: string;
}
