/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatistiqueEtudiantViewModel {
  FormationsEnCours?: number;
  FormationsTerminees?: number;
  TotalFormationsInscrites?: number;
}
