/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PointStatistique } from '../models/point-statistique';
export interface StatistiqueEvolutionViewModel {
  EvolutionFormations?: Array<PointStatistique> | null;
  EvolutionFormationsParSpecialite?: Array<PointStatistique> | null;
  EvolutionInscriptions?: Array<PointStatistique> | null;
  EvolutionUtilisateurs?: Array<PointStatistique> | null;
}
