/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatistiqueAdminViewModel {
  TotalEtudiants?: number;
  TotalFormateurs?: number;
  TotalFormations?: number;
  TotalInscriptions?: number;
  TotalUtilisateurs?: number;
  UtilisateursActifs?: number;
  UtilisateursInactifs?: number;
}
