/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormateurInfoViewModel } from '../models/formateur-info-view-model';
export interface StatistiqueFormateurViewModel {
  Formateur?: FormateurInfoViewModel;
  FormationsEnCours?: number;
  TotalEtudiants?: number;
  TotalFormations?: number;
}
