/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatistiqueGlobaleViewModel {
  FormationsEnCours?: number;
  MoyenneEtudiantsParFormation?: number;
  TotalFormations?: number;
  TotalInscriptions?: number;
}
