/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatistiqueFormationParSpecialite {
  NombreFormations?: number;
  NombreInscriptions?: number;
  Specialite?: string | null;
}
