/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatistiqueFormationParPeriode {
  NombreFormations?: number;
  NombreInscriptions?: number;
  Periode?: string | null;
  TauxOccupation?: number;
}
