/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserStatusViewModel {
  Email?: string | null;
  Id?: string | null;
  Nom?: string | null;
  Prenom?: string | null;
  Role?: string | null;
  UtilisateurActive?: boolean;
}
