/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Inscription } from '../models/inscription';
import { Role } from '../models/role';
export interface Utilisateur {
  AccessFailedCount?: number;
  ConcurrencyStamp?: string | null;
  Email?: string | null;
  EmailConfirmed?: boolean;
  Id?: string | null;
  Inscriptions?: Array<Inscription> | null;
  LockoutEnabled?: boolean;
  LockoutEnd?: string | null;
  Nom: string;
  NomComplet?: string | null;
  NormalizedEmail?: string | null;
  NormalizedUserName?: string | null;
  PasswordHash?: string | null;
  PhoneNumber?: string | null;
  PhoneNumberConfirmed?: boolean;
  Prenom: string;
  Role?: Role;
  SecurityStamp?: string | null;
  Specialite?: string | null;
  TwoFactorEnabled?: boolean;
  UserName?: string | null;
  UtilisateurActive?: boolean;
}
