/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatistiqueFormationParSpecialite } from '../../models/statistique-formation-par-specialite';

export interface ApiStatistiqueSpecialitesGet$Params {
}

export function apiStatistiqueSpecialitesGet(http: HttpClient, rootUrl: string, params?: ApiStatistiqueSpecialitesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StatistiqueFormationParSpecialite>>> {
  const rb = new RequestBuilder(rootUrl, apiStatistiqueSpecialitesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StatistiqueFormationParSpecialite>>;
    })
  );
}

apiStatistiqueSpecialitesGet.PATH = '/api/Statistique/specialites';
