/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatistiqueFormationParPeriode } from '../../models/statistique-formation-par-periode';

export interface ApiStatistiquePeriodesGet$Params {
}

export function apiStatistiquePeriodesGet(http: HttpClient, rootUrl: string, params?: ApiStatistiquePeriodesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StatistiqueFormationParPeriode>>> {
  const rb = new RequestBuilder(rootUrl, apiStatistiquePeriodesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StatistiqueFormationParPeriode>>;
    })
  );
}

apiStatistiquePeriodesGet.PATH = '/api/Statistique/periodes';
