/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatistiqueFormateurViewModel } from '../../models/statistique-formateur-view-model';

export interface ApiStatistiqueFormateurFormateurIdGet$Params {
  formateurId: string;
}

export function apiStatistiqueFormateurFormateurIdGet(http: HttpClient, rootUrl: string, params: ApiStatistiqueFormateurFormateurIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StatistiqueFormateurViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiStatistiqueFormateurFormateurIdGet.PATH, 'get');
  if (params) {
    rb.path('formateurId', params.formateurId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatistiqueFormateurViewModel>;
    })
  );
}

apiStatistiqueFormateurFormateurIdGet.PATH = '/api/Statistique/formateur/{formateurId}';
