/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatistiqueEtudiantViewModel } from '../../models/statistique-etudiant-view-model';

export interface ApiStatistiqueEtudiantEtudiantIdGet$Params {
  etudiantId: string;
}

export function apiStatistiqueEtudiantEtudiantIdGet(http: HttpClient, rootUrl: string, params: ApiStatistiqueEtudiantEtudiantIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StatistiqueEtudiantViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiStatistiqueEtudiantEtudiantIdGet.PATH, 'get');
  if (params) {
    rb.path('etudiantId', params.etudiantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatistiqueEtudiantViewModel>;
    })
  );
}

apiStatistiqueEtudiantEtudiantIdGet.PATH = '/api/Statistique/etudiant/{etudiantId}';
