/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatistiqueGlobaleViewModel } from '../../models/statistique-globale-view-model';

export interface ApiStatistiqueGlobalesGet$Params {
}

export function apiStatistiqueGlobalesGet(http: HttpClient, rootUrl: string, params?: ApiStatistiqueGlobalesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StatistiqueGlobaleViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiStatistiqueGlobalesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatistiqueGlobaleViewModel>;
    })
  );
}

apiStatistiqueGlobalesGet.PATH = '/api/Statistique/globales';
