/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InscriptionViewModel } from '../../models/inscription-view-model';

export interface ApiInscriptionInscriptionPost$Params {
  FormationId: string;
}

export function apiInscriptionInscriptionPost(http: HttpClient, rootUrl: string, params: ApiInscriptionInscriptionPost$Params, context?: HttpContext): Observable<StrictHttpResponse<InscriptionViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiInscriptionInscriptionPost.PATH, 'post');
  if (params) {
    rb.query('FormationId', params.FormationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InscriptionViewModel>;
    })
  );
}

apiInscriptionInscriptionPost.PATH = '/api/Inscription/inscription';
