/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateFormationViewModel } from '../../models/create-formation-view-model';
import { Formation } from '../../models/formation';

export interface ApiFormationPost$Params {
      body?: CreateFormationViewModel
}

export function apiFormationPost(http: HttpClient, rootUrl: string, params?: ApiFormationPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Formation>> {
  const rb = new RequestBuilder(rootUrl, apiFormationPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Formation>;
    })
  );
}

apiFormationPost.PATH = '/api/Formation';
