/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthResponseViewModel } from '../../models/auth-response-view-model';
import { RegisterViewModel } from '../../models/register-view-model';

export interface ApiAccountRegisterPost$Params {
      body?: RegisterViewModel
}

export function apiAccountRegisterPost(http: HttpClient, rootUrl: string, params?: ApiAccountRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResponseViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiAccountRegisterPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthResponseViewModel>;
    })
  );
}

apiAccountRegisterPost.PATH = '/api/Account/register';
