/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminUpdateFormateurViewModel } from '../../models/admin-update-formateur-view-model';
import { FormateurViewModel } from '../../models/formateur-view-model';

export interface ApiAdminFormateursIdPut$Params {
  id: string;
      body?: AdminUpdateFormateurViewModel
}

export function apiAdminFormateursIdPut(http: HttpClient, rootUrl: string, params: ApiAdminFormateursIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<FormateurViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiAdminFormateursIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormateurViewModel>;
    })
  );
}

apiAdminFormateursIdPut.PATH = '/api/Admin/formateurs/{id}';
