/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminCreateFormateurViewModel } from '../../models/admin-create-formateur-view-model';
import { FormateurViewModel } from '../../models/formateur-view-model';

export interface ApiAdminFormateursPost$Params {
      body?: AdminCreateFormateurViewModel
}

export function apiAdminFormateursPost(http: HttpClient, rootUrl: string, params?: ApiAdminFormateursPost$Params, context?: HttpContext): Observable<StrictHttpResponse<FormateurViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiAdminFormateursPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormateurViewModel>;
    })
  );
}

apiAdminFormateursPost.PATH = '/api/Admin/formateurs';
