/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormateurViewModel } from '../../models/formateur-view-model';

export interface ApiAdminFormateursIdGet$Params {
  id: string;
}

export function apiAdminFormateursIdGet(http: HttpClient, rootUrl: string, params: ApiAdminFormateursIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FormateurViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiAdminFormateursIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormateurViewModel>;
    })
  );
}

apiAdminFormateursIdGet.PATH = '/api/Admin/formateurs/{id}';
