/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasswordResetViewModel } from '../../models/password-reset-view-model';

export interface ApiAdminFormateursIdResetPasswordPost$Params {
  id: string;
}

export function apiAdminFormateursIdResetPasswordPost(http: HttpClient, rootUrl: string, params: ApiAdminFormateursIdResetPasswordPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PasswordResetViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiAdminFormateursIdResetPasswordPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PasswordResetViewModel>;
    })
  );
}

apiAdminFormateursIdResetPasswordPost.PATH = '/api/Admin/formateurs/{id}/reset-password';
