/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormationDetailViewModel } from '../../models/formation-detail-view-model';

export interface ApiEspaceFormateurFormationsFormationIdGet$Params {
  formationId: string;
}

export function apiEspaceFormateurFormationsFormationIdGet(http: HttpClient, rootUrl: string, params: ApiEspaceFormateurFormationsFormationIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FormationDetailViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiEspaceFormateurFormationsFormationIdGet.PATH, 'get');
  if (params) {
    rb.path('formationId', params.formationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormationDetailViewModel>;
    })
  );
}

apiEspaceFormateurFormationsFormationIdGet.PATH = '/api/EspaceFormateur/formations/{formationId}';
