/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormateurEspaceViewModel } from '../../models/formateur-espace-view-model';

export interface ApiEspaceFormateurDashboardGet$Params {
}

export function apiEspaceFormateurDashboardGet(http: HttpClient, rootUrl: string, params?: ApiEspaceFormateurDashboardGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FormateurEspaceViewModel>> {
  const rb = new RequestBuilder(rootUrl, apiEspaceFormateurDashboardGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FormateurEspaceViewModel>;
    })
  );
}

apiEspaceFormateurDashboardGet.PATH = '/api/EspaceFormateur/dashboard';
