/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EtudiantInscritViewModel } from '../../models/etudiant-inscrit-view-model';

export interface ApiEspaceFormateurFormationsFormationIdEtudiantsGet$Params {
  formationId: string;
}

export function apiEspaceFormateurFormationsFormationIdEtudiantsGet(http: HttpClient, rootUrl: string, params: ApiEspaceFormateurFormationsFormationIdEtudiantsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EtudiantInscritViewModel>>> {
  const rb = new RequestBuilder(rootUrl, apiEspaceFormateurFormationsFormationIdEtudiantsGet.PATH, 'get');
  if (params) {
    rb.path('formationId', params.formationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EtudiantInscritViewModel>>;
    })
  );
}

apiEspaceFormateurFormationsFormationIdEtudiantsGet.PATH = '/api/EspaceFormateur/formations/{formationId}/etudiants';
